server:
  port: 8080
spring:
  profiles:
    active: dev
---
customVariables:
  variable1: Mi primer variable 1
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost/UsuariosCurso?useSSL=false&serverTimezone=UTC
    dbname: UsuariosCurso
    username: root
    password: n0m3l0
    driver-class-name: com.mysql.cj.jdbc.Driver
security:
  jwt:
    secret: ghk45jgherogho834go3h4g
    issuer: Main
    ttlMillis: 604800000
    
---
customVariables:
  variable1: Mi primer variable 2
spring:
  config:
    activate:
      on-profile: qa
  datasource:
    url: jdbc:mysql://localhost/UsuariosCurso?useSSL=false&serverTimezone=UTC
    dbname: UsuariosCurso
    username: root
    password: n0m3l0
    driver-class-name: com.mysql.cj.jdbc.Driver
security:
  jwt:
    secret: ghk45jgherogho834go3h4g
    issuer: Main
    ttlMillis: 604800000